### ISSUE TITLE
@hide & @invisible gm causes chat issue

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#194]
GMs name appears as ID

?20929302: sometext

**Comment by mekolat** [comment]
This is because if the gm is invisible it is not sent to other players (`being_visible`) so manaplus does not know the gm exists. The chat packets only sends being id and text. Since manaplus doesn't know who the id belongs to it shows `?<id>`.

- - -
there are some solutions possible though:
- Silently convert any chat message to local broadcast (not logged) if the gm is invisible. Send the local broadcast only to players in range instead of the whole map, like a normal chat message.
  - `global announcement from XYZ: message`
- Send id 0 when the gm is invisible.
  - `?0: message`
- Discard any chat message when the gm is invisible
- Quickly send `being_visible` (with class 127 so it's invisible), the message, and then `being_remove`
  - `XYZ: message`
- Send the message as `script_message` (displays on top of the PLAYER (not the gm), and in chat) to everyone in visible range
  - `XYZ: message`

**Comment by 4144** [comment]
Or other solution,
revert o11c changes where he removed nicks from chat messages.

**Comment by mekolat** [comment]
@4144 any idea why @o11c removed nicks from messages?

**Comment by mekolat** [comment]
@4144 I have an idea
- normal messages are sent as `<message>`, along with the being id
- messages from invisible beings are sent as `<nick>:<message>`, with being id `0`

whenever the id is `0`, manaplus should treat the *first* `:` it finds as a separator (any other `:` is part of the message)

**Comment by 4144** [comment]
why not send id?
And why not send nick always? In some cases client cant find nick and will show ?id for normal players too.

**Comment by mekolat** [comment]
@4144 because I have no idea why nicks were removed in the first place, but fine, let's do it

**Comment by o11c** [comment]
Originally, player names can be spoofed. I don't remember what exactly I changed though.

**Comment by bjorn** [comment]
> Originally, player names can be spoofed. I don't remember what exactly I changed though.

It appears to have been an unintended side-effect of 8b5370313dcc00a45ea5c3e8b4c497bc00fd8e13 then, which changed the return value of `clif_validate_chat` to be only the message part, whereas previously it still included the name. In any case the new approach implemented in 2ba1812b8315b5df8291f68144b0c380a6cd749d is preferable.
