### ISSUE TITLE
need a way to check when the player is doing nothing

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#52]
Take a look at [parua.txt](https://github.com/themanaworld/tmwa-server-data/blob/master/world/map/npc/029-3/parua.txt#L342). To detect if you are idle it checks the position you have at the start of the round and compares it to the position you had at the start of the previous round. This is problematic because even if you are moving you can be detected as idle because you walked on the same tile.

To remedy to this we need builtin that checks if the player is idle. Hercules's [checkidle](https://github.com/HerculesWS/Hercules/blob/master/src/map/script.c#L16136) builtin would probably be a good choice. 

@wushin

**Comment by Deepthought-TMW** [comment]
Why not take positions of players set @candor_oldx, @candor_x; set @candor_oldy, @candor_y; after the summoning of monsters. Add a small time delay before taking the positions. Otherwise make candor_x, candor_y arrays and take position of players in some time intervel and use boolean logic to determine whether they are idle or not.
